// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PokeBuildExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "PokeBuild.455fbf38-de00-4c22-8ac1-96c1206a1586";
        public const string Name = "Poke Build";
        public const string Description = @"Build System of the PokeEngine.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Stefano Famà";
        public const string Tags = "";
    }
}
